/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function detectLang(input: string, iso6393?: boolean | undefined | null): string
export function detectScript(input: string): string
